# Coding a Single Neuron
## Method 1: Specify everything explicitly

In this version, we will need to specify the input, parameters, and operations explicitly. While this is fine for a small example, it should start to feel impractical as the number of inputs and parameters increases, even for a single neuron. But, it is a good place to start to learn exactly what a neuron does. To start, let's recall the details of a single neuron:

<img src="single_neuron.jpeg" width=600 align="center">

We first need to store the input values in separate variables. Here, we are considering only one *sample* (think of this like one row of data from a spreadsheet) and each sample has only *two* features (think of this like two columns from a spreadsheet). In a more realistic setting, we could have thousands or millions of samples to deal with, and each one could have hundreds of features. 

In [1]:
x_1 = 3 
x_2 = 4

We now need to specify the parameters: the *weights* and *bias*. We need one weight for each input feature. Later we will see how the neuron *learns* the best values for the weights and bias. At this point we are doing what is called *weight initialization*: picking starting values for the weights and bias. 

In [2]:
w_1 = 1
w_2 = 0

b = 3

The next step is to specify the first *mathematical operation* that the neuron perfoms: a linear transformation. 

In [3]:
z = w_1 * x_1 + w_2 * x_2 + b
z

6

And now we perform the final mathematical operation, which is applying the *activation function* to the output of the previous step. Here, we are using the *ReLU* function, or *Rectified Linear Unit*. 

In [4]:
a = max(0, z)
a

6

The output above is the **$\hat y$** in the image above. 

## Method 2: Using NumPy arrays 

There are at least two problems with **Method 1**. The first is that as the number of inputs increases, for example, imagine samples with 1000 features, this approach is impractical as you would need to specify 1000 variables for the input data and 1000 variables for the weights which ends up being a lot of unnecessary typing (if you don't believe it, try doing it!). The second problem is that we are not taking advantage of packages like NumPy that optimize for these mathematical operations. 

So, for this method, we will repeat the example we did for Method 1 but use arrays and array operations instead.

In [5]:
import numpy as np

x = np.array([3, 4])
w = np.array([1, 0])

# the next statement is similar to "b = 3" 
# this may look odd but will help later when we have more than one neuron and thus more than one bias
b = np.array(3) 

We can now take advantage of NumPy's optimized method for doing mathematical operations with arrays. If we consider the weights and the features to be vectors: 

$$\boldsymbol{w} = [ w_1, w_2] \\
\boldsymbol{x} = [x_1, x_2] $$

Then all we need to do is calculate what is called the *dot product* of these two vectors:

$$\rm{np.dot}(\boldsymbol{w}, \boldsymbol{x}) = w_1 x_1 + w_2 x_2$$

In [6]:
z = np.dot(w, x.T) + b
z

6

In [7]:
a = max(0, z)
a

6

We see that we get the same result as we did with Method 1. However, we could now use Pandas to read in a .csv file and store that in a NumPy array (our $x$ variable in the above code) and have a much quicker method for getting the input data into our code. Although there will be no speed difference for examples like ours with only a few numbers, we will notice a difference when we have thousands of samples and thousands of features. 

### Extending Method 2: Multiple samples

Our examples so far have only consider one sample, which would never be the case for a real application. Using arrays allows us to extend the operation of a single neuron to multiple samples. The code below repeats what we did above except for two samples.

So, in the example below, the input [3, 4] is passed through the single neuron to produce a single output and then the input [2, 5] is passed through the single neuron to produce another single output. 

In [8]:
x = np.array([[3, 4], [2, 5]])
w = np.array([1, 0])
b = np.array(3) 

In [9]:
z = np.dot(w, x.T) + b
z

array([6, 5])

In [10]:
a = np.maximum(0, z)
a

array([6, 5])

We now see that the final output is an array with two numbers. Here the output 6 is associated with the input [3, 4] and the output 5 is associated with the input [2, 5]. 

## Method 3: Creating reusable objects

While Method 2 is an improvement over Method 1, we can do even better by taking advantage of the fact that Python is an object-oriented programming language. For this course, you do not need to worry about being able write your own Python **classes**. What I would like you to focus on is how this simplifies what we are trying to accomplish: create a network out of a bunch of neurons where each neuron has the same fundamental structure and operation. 

To do this, we can use the **class** keyword instead of having to write similar code over and over again for each neuron. We can think of a class as a recipe for a particular type of object. And an object is a collection of *variables* and *functions* (also called *methods*) that act on those variables.

In the code below, we are creating a recipe for a single neuron. **Please note that we have not yet created an actual neuron.** This is similar to the difference between having a recipe for baking a loaf of bread and actually baking a loaf of bread. 

We know that any neuron needs to have weights and a bias. That is what the **__init__** function takes care of. We also know that our neuron has to perform certain mathematical operations on the input, weights, and bias and provide an output. That is what the **feedforward** function takes care of.

In [15]:
# This code is based on code written by Victor Zhou
# License for reuse: https://github.com/vzhou842/neural-network-from-scratch/blob/master/LICENSE

class Neuron:
  # sets the value of the weights and the bias
  def __init__(self, weights, bias):
    self.weights = weights
    self.bias = bias

  # defines the mathematical operations to be done on the inputs, weights, and bias to produce the output
  def feedforward(self, inputs):
    z = np.dot(self.weights, inputs.T) + self.bias
    a = np.maximum(0, z)
    return a

Let's define some values for the weights and bias.

In [16]:
w = np.array([1, 0]) 
b = np.array(3)                  

Now let's use the recipe to create a single (specific) neuron. (That is, we are now using the recipe to bake a particular loaf of bread.)

In [17]:
my_neuron = Neuron(w, b)  

The line of code above creates a neuron with specific values for the weights and bias. It also already has a function that we can use to carry out the appropriate mathematical operations of our neuron to produce output whenever we supply values for the input:

In [14]:
x = np.array([[3, 4], [2, 5]])      

my_neuron.feedforward(x)  

array([6, 5])