# Coding One Hidden Layer

## Exercises

To complete these exercises, you will need to refer to the *coding_one_hidden_layer.ipynb* file. It's best if you reproduce any necessary code in a separate cell below as you complete these exercise.

 1. Using pencil and paper, draw an appropriate diagram and then perform all the necessary mathematical operations to calculate the output of network given the following information:
     - $X = \left[\begin{array}{cc} 1 & -6 \\
     -4 & 2 \end{array}\right]$ 
     - $W^{[1]} = \left[\begin{array}{cc} 2 & 1 \\
     1 & 3 \end{array}\right]$
     - $b^{[1]} = [3, 4]$
     - $W^{[2]} = [3, 1]$
     - $b^{[2]} = [2]$
     - sigmoid activation function

Take a picture of your drawing and insert it here: 

 2. Use **Method 1** code to double check your calculation from Exercise 1.  


In [1]:
x_1 = 1
x_2 = -6
w1_N1_L1 = 2
w2_N1_L1 = 1
b_N1_L1 = 3

w1_N2_L1 = 1
w2_N2_L1 = 3
b_N2_L1 = 4

z_N1_L1 = w1_N1_L1 * x_1 + w2_N1_L1 * x_2 + b_N1_L1
z_N2_L1 = w1_N2_L1 * x_1 + w2_N2_L1 * x_2 + b_N2_L1

print("z_N1_L1 = ", z_N1_L1)
print("z_N2_L1 = ", z_N2_L1)

z_N1_L1 =  -1
z_N2_L1 =  -13


In [2]:
import numpy as np

def sigmoid(z):
    a = 1 / (1 + np.exp(-z))
    return a

a_N1_L1 = sigmoid(z_N1_L1)
a_N2_L1 = sigmoid(z_N2_L1)

print("The output of N1_L1 is: ", a_N1_L1)
print("The output of N2_L1 is: ", a_N2_L1)

The output of N1_L1 is:  0.2689414213699951
The output of N2_L1 is:  2.2603242979035746e-06


In [3]:
w1_N1_L2 = 3
w2_N1_L2 = 1
b_N1_L2 = 2

z_N1_L2 = w1_N1_L2 * a_N1_L1 + w2_N1_L2 * a_N2_L1 + b_N1_L2

print("z_N1_L2 = ", z_N1_L2)

a_N1_L2 = sigmoid(z_N1_L2)

print("The output of N1_L2 is: ", a_N1_L2)

z_N1_L2 =  2.806826524434283
The output of N1_L2 is:  0.9430436037765143


 3. Modify the `__init__` function of **Method 3** so it initializes the weights to random numbers between 0 and 1 and the biases to all have the value of 1. (Hint: Use `numpy` functions to do this.) Check that it works by:
 - creating a network using the data for `X` from Exercise 1
 - printing out the value of the weights for this network
 - printing out the value of the biases for this network


In [21]:
# Inspired by code written by Victor Zhou
# License for reuse: https://github.com/vzhou842/neural-network-from-scratch/blob/master/LICENSE

import numpy as np # included again here for completeness; normally this should only occur once in your notebook

class OurNeuralNetwork:
  '''
  A neural network with:
    - 2 inputs
    - a hidden layer with 2 neurons (h1, h2)
    - an output layer with 1 neuron (o1)
  '''
  def __init__(self, input_size, hidden_size, output_size):
        # Initialize weights with random values between 0 and 1
        self.w1 = np.random.rand(hidden_size, input_size)
        self.w2 = np.random.rand(output_size, hidden_size)        
        # Initialize biases with all values set to 1
        self.b1 = np.ones((hidden_size, 1))
        self.b2 = np.ones((output_size, 1))
        print(self.w1, self.w2, self.b1, self.b2)
  
  def activation(self, z):
    a = 1 / (1 + np.exp(-z))
    return a

  def feedforward(self, input):
    Z1 = np.dot(self.w1, input.T) + self.b1
    A1 = self.activation(Z1)
    Z2 = np.dot(self.w2, A1) + self.b2
    A2 = self.activation(Z2)

    out = A2

    return out

In [22]:
network = OurNeuralNetwork(2, 2, 1)

[[0.97359214 0.65950894]
 [0.74772987 0.58361251]] [[0.17225832 0.61416678]] [[1.]
 [1.]] [[1.]]


In [23]:
x = np.array([[-1, 6], [-4, 2]])

network.feedforward(x) 

array([[0.85436045, 0.77150752]])

 4. Modify **Method 3** so that the `OuNeuralNetwork` will accept input data that has 3 features. 
     - Use the initialization method from Exercise 3
     - Draw a diagram
     - Test that it works, that is, produces an output without error, using:
     $$ X = \left[\begin{array}{ccc} -1 & 3 & 2\\
     5 & 1 & 4 \end{array}\right] $$
     - What did you have to modify for this to work?


In [4]:
# Inspired by code written by Victor Zhou
# License for reuse: https://github.com/vzhou842/neural-network-from-scratch/blob/master/LICENSE

import numpy as np # included again here for completeness; normally this should only occur once in your notebook

class OurNeuralNetwork:
  '''
  A neural network with:
    - 2 inputs
    - a hidden layer with 2 neurons (h1, h2)
    - an output layer with 1 neuron (o1)
  '''
  def __init__(self, input_size, hidden_size, output_size):
        # Initialize weights with random values between 0 and 1
        self.w1 = np.random.rand(hidden_size, input_size)
        self.w2 = np.random.rand(output_size, hidden_size)
        # Initialize biases with all values set to 1
        self.b1 = np.ones((hidden_size, 1))
        self.b2 = np.ones((output_size, 1))        
        print(self.w1, self.w2, self.b1, self.b2)
  
  def activation(self, z):
    a = 1 / (1 + np.exp(-z))
    return a

  def feedforward(self, input):
    Z1 = np.dot(self.w1, input.T) + self.b1
    A1 = self.activation(Z1)
    Z2 = np.dot(self.w2, A1) + self.b2
    A2 = self.activation(Z2)

    out = A2

    return out

In [5]:
network = OurNeuralNetwork(3, 2, 1)

[[0.11443096 0.62161502 0.47326306]
 [0.92647739 0.12997245 0.96366589]] [[0.03770101 0.83925147]] [[1.]
 [1.]] [[1.]]


In [6]:
x = np.array([[-1, 3, 2], [5, 1, 4]])

network.feedforward(x) 

array([[0.85883465, 0.86718256]])

 5. Modify **Method 3** so that the network you created in Exerecise 4 has 3 neurons in hidden layer 1.  
     - Use the initialization method from Exercise 3
     - Draw a diagram
     - Test that it works, that is, produces an output without error, using:
     $$ X = \left[\begin{array}{ccc} -1 & 3 & 2\\
     5 & 1 & 4 \end{array}\right] $$
     - What did you have to modify for this to work?


In [43]:
# Inspired by code written by Victor Zhou
# License for reuse: https://github.com/vzhou842/neural-network-from-scratch/blob/master/LICENSE

import numpy as np # included again here for completeness; normally this should only occur once in your notebook

class OurNeuralNetwork:
  '''
  A neural network with:
    - 2 inputs
    - a hidden layer with 2 neurons (h1, h2)
    - an output layer with 1 neuron (o1)
  '''
  def __init__(self, input_size, hidden_size, output_size):
        # Initialize weights with random values between 0 and 1
        self.w1 = np.random.rand(hidden_size, input_size)
        self.w2 = np.random.rand(self.w1.shape[0], input_size)
        self.w3 = np.random.rand(output_size, hidden_size)
        # Initialize biases with all values set to 1
        self.b1 = np.ones((hidden_size, 1))
        self.b2 = np.ones((self.b1.shape[1], 1))
        self.b3 = np.ones((output_size, 1))        
        print(self.w1, self.w2, self.w3, self.b1, self.b2, self.b3)
  
  def activation(self, z):
    a = 1 / (1 + np.exp(-z))
    return a

  def feedforward(self, input):
    Z1 = np.dot(self.w1, input.T) + self.b1
    A1 = self.activation(Z1)
    Z2 = np.dot(self.w2, A1) + self.b2
    A2 = self.activation(Z2)

    out = A2

    return out

In [44]:
network = OurNeuralNetwork(3, 2, 1)

[[0.73122037 0.41560074 0.78753129]
 [0.33204809 0.26515383 0.13407587]] [[0.27602142 0.63959757 0.24332673]
 [0.2451438  0.44478156 0.49477167]] [[0.32340199 0.69799098]] [[1.]
 [1.]] [[1.]] [[1.]]


In [33]:
x = np.array([[-1, 3, 2], [5, 1, 4]])

network.feedforward(x) 

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

 6. Modify **Method 3** so that your network will accept input data with any number of features and the hidden layer (layer 1) will contain the number of neurons specified by the user. Hint: it might help if creating this class took 2 parameters, as in `OurNeuralNetwork(number_of_features, number_of_neurons_in_hidden_layer)`.    
     - Use the initialization method from Exercise 3
     - Draw a diagram
     - Test that it works using input that has different number of features and choosing different numbers of neurons for layer 1
     - What did you have to modify for this to work?

In [37]:
# Inspired by code written by Victor Zhou
# License for reuse: https://github.com/vzhou842/neural-network-from-scratch/blob/master/LICENSE

import numpy as np # included again here for completeness; normally this should only occur once in your notebook

class OurNeuralNetwork:
  '''
  A neural network with:
    - 2 inputs
    - a hidden layer with 2 neurons (h1, h2)
    - an output layer with 1 neuron (o1)
  '''
  def __init__(self, input_size, number_of_neurons, output_size):
        # Initialize weights with random values between 0 and 1
        self.w = [np.random.rand(number_of_neurons, input_size)]
        self.wl = np.random.rand(output_size, number_of_neurons)
        
        # Initialize biases with all values set to 1
        self.b1 = np.ones((number_of_neurons, 1))
        self.b2 = np.ones((output_size, 1))        
        print(self.w, self.wl, self.b1, self.b2)
  
  def activation(self, z):
    a = 1 / (1 + np.exp(-z))
    return a

  def feedforward(self, input):
    Z1 = np.dot(self.w, input.T) + self.b1
    A1 = self.activation(Z1)
    Z2 = np.dot(self.wl, A1) + self.b2
    A2 = self.activation(Z2)

    out = A2

    return out

In [41]:
network = OurNeuralNetwork(3, 4, 1)

[array([[0.0022048 , 0.67552028, 0.6460005 ],
       [0.31934908, 0.86474987, 0.41507844],
       [0.18136551, 0.10578597, 0.58174061],
       [0.26357737, 0.0517417 , 0.84406057]])] [[0.7105497  0.88317061 0.67496243 0.79559625]] [[1.]
 [1.]
 [1.]
 [1.]] [[1.]]


In [42]:
x = np.array([[-1, 3, 2], [5, 1, 4]])

network.feedforward(x) 

array([[[0.98060221, 0.98267325]]])