## Practice Lab 2: Decision tree from scratch (well, we hope!)

### Decision Trees
- Benefits
    - Generalize
    - No assumptions about the data
    - Interpretable
    - Feature importance
- Drowbacks
    - Tend to overfit

### Decision Tree Regressor Recipe

- Decide the features and target variables.

- Split the data:
    - split the split points for all features!
    - Pick the error to use.
    - Calculate an error for the root node.
    - Make and calculate errors for each split.

- Select and use the best split:
    - Best split = least error.

- Repeat the for the nest nodes( True/Right and False/Left):


### Part 1
- create random list of 5 integers
 - create a function that will find the split values by
     - sorting the list from lowest to highest value
     - finding the midpoint for each consecutive pair of values
     - returning midpoints as a list
 - create new random list of 5 integers and test your split values function 

> wherever you see `list` you can always substitute with `ndarray` if more appropriate

In [2]:
import random
import numpy as np

In [28]:
rl = random.sample(range(0,100),5)
rl
print(rl)
type(rl)

[41, 87, 78, 58, 6]


list

In [26]:
mid = []
def split(list):
    list = sorted(list)
    print(list)
    for i in range(len(list) - 1):
        m = (list[i] +list[i+1])/2
        mid.append(m)
        
    return mid

In [27]:
raj = [1,2,3,4,5,6,7,100]
raj[3] = 20
print(raj)
split(raj)

[1, 2, 3, 20, 5, 6, 7, 100]
[1, 2, 3, 5, 6, 7, 20, 100]


[1.5, 2.5, 4.0, 5.5, 6.5, 13.5, 60.0]

In [29]:
split(rl)
mid

[6, 41, 58, 78, 87]


[1.5, 2.5, 4.0, 5.5, 6.5, 13.5, 60.0, 23.5, 49.5, 68.0, 82.5]

In [7]:
rm = random.sample(range(0,100),5)
print(rm)
split(rm)
print(mid)

[46, 75, 9, 56, 54]
[9, 46, 54, 56, 75]
[1.5, 2.5, 4.0, 5.5, 6.5, 13.5, 60.0, 19.0, 43.5, 76.5, 95.0, 27.5, 50.0, 55.0, 65.5]


### Part 2
 - create random array of integers in shape (5, 3)
 - create a function that iterates over the columns and calculates the split points for each column
 - return as a dictionary with column name as key and list of split points as value
 - verify by hand that you are getting the correct split points

In [8]:
# create random array of integers in shape (5, 3)
ra = np.random.randint(low = 0, high = 100, size = (5, 3))
print(ra)
 
# create a function that iterates over the columns and calculates the split points for each column
def split_row(arg):
    cols = arg.shape[1]
    rows = arg.shape[0]
    mid_ = []
    for col in range(cols):
        column = arg[:, col]
        sorted_col = np.sort(column)
        mid = [(sorted_col[i] + sorted_col[i+1]) / 2 for i in range(len(sorted_col)-1)]
        mid_.append(mid)
           

    return mid_
    
        
    

[[97 90 85]
 [60 54  3]
 [59 26 61]
 [49 37 27]
 [73  9 86]]


In [9]:
split_row(ra)

[[54.0, 59.5, 66.5, 85.0], [17.5, 31.5, 45.5, 72.0], [15.0, 44.0, 73.0, 85.5]]

### Part 3
 - create random array of integers in shape (5, 2)
 - use the first column as feature data X and the second column as regression target y
 - create a function that takes in this array and
     - calculates the MSE of the root node
     - calculates the split points
     - for each split point
         - split the data into two parts
         - calculates the weighted MAE after the split
     - returns the split point (and the new MAE) that reduces the MAE of the root node the most
     
> Note: this function could use other funtions that perform the individual steps

In [10]:
rb = np.random.randint(low = 0, high = 100, size = (5, 2))
print(rb)
X = rb[:, 0]
print(X)
Y = rb[:, 1]
print(Y)

[[52 95]
 [50  1]
 [ 8 78]
 [79 11]
 [95 60]]
[52 50  8 79 95]
[95  1 78 11 60]


In [30]:
Y

[1, 11, 60, 78, 95]

In [11]:
Y = sorted(Y)
split(Y)

#calculates the MSE of the root node
Y_avg = np.mean(Y)
print(Y_avg)
print(Y - Y_avg)
print(np.sum((Y - Y_avg)**2))
mse = np.mean((Y - Y_avg)**2)
mse

[1, 11, 60, 78, 95]
49.0
[-48. -38.  11.  29.  46.]
6826.0


1365.2

### Part 4 (Optional)
 - Modify **Part 3** code so that it can handle more than 1 feature